# Generated by Django 5.2.1 on 2025-06-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('tech_stack', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to='project_thumbnails/')),
                ('download_link', models.FileField(blank=True, null=True, upload_to='project_files/')),
                ('status', models.CharField(choices=[('finished', 'Finished'), ('not_finished', 'Not Finished')], max_length=20)),
                ('category', models.CharField(choices=[('desktop', 'Desktop App'), ('web', 'Web App'), ('mobile', 'Mobile App')], max_length=50)),
            ],
        ),
    ]
