# Generated by Django 5.2.3 on 2025-06-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('tech_stack', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('programming', 'Programming langauge'), ('library', 'Library and Frameworks'), ('database', 'Database'), ('others', 'Others')], max_length=50)),
            ],
        ),
    ]
