# Generated by Django 5.2.3 on 2025-06-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_technical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technical',
            name='tech_stack',
        ),
    ]
