# Generated by Django 5.2.3 on 2025-06-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_technical_tech_stack'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technical',
            options={'ordering': ['category', 'title']},
        ),
        migrations.AddField(
            model_name='technical',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='technical_skills/'),
        ),
        migrations.AlterField(
            model_name='technical',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming Languages'), ('framework', 'Frameworks & Libraries'), ('database', 'Databases'), ('other', 'Others')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='technical',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
